package:
  name: pymoos
  version: '2021.1'

source:
  path: ..

build:
  number: 0
  script: python -m pip install . -vvv

requirements:
  build:
    - {{ compiler('cxx') }}

  host:
    - python
    - pip
    - pybind11 >=2.9.0

  run:
    - python


test:
  imports:
    - pymoos
  source_files:
    - tests
  commands:
    - python tests/test.py

about:
  summary: MOOS Python Wrapper.
  license_file: LICENSE
